'use strict';

const path = require('path');
const express = require('express');
const basicAuth = require('express-basic-auth');
const { waitForDb } = require('./db');
const { ensureSchema } = require('./lib/migrate');

const PORT = process.env.PORT || 3000;

async function main() {
  await waitForDb();
  // db/init only runs against an empty data dir, so an existing deployment
  // needs the newer columns applied here before any route touches them.
  await ensureSchema();

  const app = express();
  app.set('view engine', 'ejs');
  app.set('views', path.join(__dirname, 'views'));
  app.use(express.urlencoded({ extended: true }));
  app.use(express.static(path.join(__dirname, 'public')));

  // Defense in depth: this is the answer key for the benchmark, so it's
  // also basic-auth gated on top of never being reachable from the
  // attack-box network (see docker-compose.yml). Credentials come from
  // .env, generated by up.sh alongside the attack-box password.
  if (process.env.DASHBOARD_PASSWORD) {
    app.use(
      basicAuth({
        users: { [process.env.DASHBOARD_USER || 'admin']: process.env.DASHBOARD_PASSWORD },
        challenge: true,
        realm: 'Insomnia Benchmark Lab',
      })
    );
  } else {
    console.warn('WARNING: DASHBOARD_PASSWORD not set — dashboard is running with no auth.');
  }

  app.use(require('./routes/labs'));
  app.use(require('./routes/upload'));
  app.use(require('./routes/scans'));
  app.use(require('./routes/compare'));
  app.use(require('./routes/vulhub'));
  app.use(require('./routes/containers'));

  app.use((req, res) => {
    res.status(404).render('error', { message: 'Not found.' });
  });

  // eslint-disable-next-line no-unused-vars
  app.use((err, req, res, next) => {
    console.error(err);
    res.status(500).render('error', { message: err.message || 'Internal error.' });
  });

  app.listen(PORT, () => {
    console.log(`Dashboard listening on :${PORT}`);
  });
}

main().catch((err) => {
  console.error('Fatal startup error:', err);
  process.exit(1);
});
